name: Build JAR

on:
  push:
    branches:
      - main
    paths:
      - '**/*'  # Trigger on any file change

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
      
    

    - name: Build with Maven
      working-directory: demo
      run: mvn clean package  # Change to your build command, e.g., `mvn package` or `./gradlew build` for Gradle
   
    - name: Build with Maven
      working-directory: demo
      run: mvn install
      
    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: my-jar-file
        path: demo/target/*.jar  # Change path if your JAR file is located elsewhere
        
    - name: Verify directory structure
      run: |
        ls -R  # List all files and directories recursively to check structure
        if [ ! -f demo/pom.xml ]; then echo "pom.xml not found in the demo directory"; exit 1; fi
